// 语言包
const messages = {
  CN: {
    mainView: {
      config: "配置",
      pwd: "密码",
      app: "小程序码",
      success: "通行成功",
      fail: "通行失败",
      passwordDisabled: "密码已禁用",
    },
    idleView: {
      week: {
        0: "周日",
        1: "周一",
        2: "周二",
        3: "周三",
        4: "周四",
        5: "周五",
        6: "周六",
      },
    },
    appView: {
      knowed: "我已知晓",
      appQrcodeLbl: "使用小程序便捷管理",
    },
    pwdView: {
      title: "密码通行",
      pwd: "请输入密码",
      pwdAccess: "确认",
      success: "密码通行成功",
      fail: "密码通行失败",
    },
    newPwdView: {
      title: "设置管理密码",
      pwdAccess: "确认",
      pwd: "请输入密码",
      confirmPwd: "请再次输入密码",
      pwdAccess: "确认",
      tip: "注意：您设置的密码位数应大于或等于 8 位，如跳过设置，设备将采用默认密码。",
      skip: "跳过，以后设置",
      success: "密码设置成功",
      fail: "密码设置失败",
      pwdNotMatch: "两次输入密码不一致",
    },
    identityVerificationView: {
      title: "身份验证",
      pwd: "请输入管理密码",
      pwdAccess: "确认",
      success: "人脸验证成功",
      fail: "人脸验证失败",
      pwdLog: "密码登录",
      faceLog: "人脸登录",
      pwdFail: "密码错误",
    },
    configView: {
      title: "设置菜单",
      localUser: "本地用户",
      networkSetting: "网络设置",
      doorControl: "门禁管理",
      systemSetting: "系统设置",
      deviceInfo: "设备信息",
      recordQuery: "记录查询",
      voiceBroadcast: "语音播报",
      cloudCert: "云证功能",
      factoryTest: "工厂测试",
      help: "使用帮助",
      confirmExit: "确认退出",
      confirmExitContent: "是否确认退出设置菜单？",
    },
    cloudCertView: {
      title: "云证功能",
      cloudCertActive: "云证激活",
      inputKey: "请输入密钥",
      key: "密钥",
      tip: "注意：云证可以通过手输密钥或扫描\n专用二维码激活，详情请联系客服。",
      save: "保存",
    },
    doorControlView: {
      title: "门禁管理",
      save: "保存",
      openDoorRelayDelay: "开门继电器延时",
      antiTamperAlarm: "防拆报警",
      input: "请输入",
      success: "保存成功",
      fail: "保存失败",
      mqttAddr: "MQTT地址",
      mqttUser: "MQTT账号",
      mqttPwd: "MQTT密码",
      onlineChecking: "在线验证",
      onlineCheckingTimeout: "在线验证超时",
      ms: "毫秒"
    },
    helpView: {
      title: "使用帮助",
      scanCode: "扫码访问官方教程",
    },
    networkSettingView: {
      title: "网络设置",
      type: "网络类型",
      ip: "IP",
      dhcp: "DHCP",
      mask: "子网掩码",
      gateway: "网关",
      dns: "DNS1",
      dns2: "DNS2",
      mac: "MAC",
      status: "网络状态",
      save: "保存",
      input: "请输入",
      ethernet: "以太网",
      wifi: "WiFi",
      _4G: "4G",
      networkUnconnected: "网络未连接",
      networkConnected: "网络已连接",
      wifiName: "WiFi名称",
      wifiPwd: "WiFi密码",
      wifiList: "WiFi列表",
      close: "关闭",
      confirm: "确认",
      fail: "保存失败",
      success: "保存成功",
    },
    systemSettingView: {
      title: "系统设置",
      displaySetting: "显示界面设置",
      faceRecognitionSetting: "人脸识别设置",
      swipeCardRecognitionSetting: "刷卡识别设置",
      passLogSetting: "通行日志设置",
      passwordOpenDoorSetting: "密码开门设置",
      passwordManagement: "密码管理",
      timeSetting: "时间设置",
      restartDevice: "重启设备",
      restoreDefaultConfig: "恢复默认配置",
      resetDevice: "重置设备",
      restart: "重启",
      restoreDefault: "恢复",
      reset: "重置",
      autoAdjustScreenBrightness: "自动调节屏幕亮度",
      screenBrightness: "屏幕亮度",
      autoTurnOffScreen: "自动熄屏",
      autoTurnOffScreenTime: "自动熄屏时间",
      autoScreenSaver: "自动屏保",
      autoScreenSaverTime: "自动屏保时间",
      displayIp: "显示IP地址",
      displayDeviceSn: "显示设备SN",
      language: "语言",
      displayCode: "显示小程序码",
      themeMode: "工作主题",
      save: "保存",
      input: "请输入",
      faceSimilarityThreshold: "人脸相似度阈值",
      livenessDetectionFunction: "活体检测功能",
      livenessDetectionThreshold: "活体检测阈值",
      infraredImageDisplay: "红外图像显示",
      maskRecognition: "口罩识别",
      maskRecognitionThreshold: "口罩识别阈值",
      recognitionDistance: "识别距离",
      imageSaveType: "图像保存类型",
      saveStrangerImage: "保存陌生人图像",
      fullView: "全景",
      face: "人脸",
      swipeCardRecognition: "刷卡核验",
      passwordOpenDoor: "密码开门",
      inputOriginalPassword: "请输入原管理密码",
      inputNewPassword: "请输入新密码",
      inputRepeatNewPassword: "请重复新密码",
      syncMode: "时区",
      ntpAddress: "NTP地址",
      timeSyncSuccess: "时间与服务器同步成功",
      success: "保存成功",
      fail: "保存失败",
      appMode: "APP模式",
      confirmation: "确认",
      confirmRestart: "确认重启吗？",
      confirmRecoveryConfiguration: "确认恢复默认配置吗？",
      confirmReset: "确认重置吗？",
      min: "分钟"
    },
    deviceInfoView: {
      title: "设备信息",
      systemInfo: "系统信息",
      dataCapacityInfo: "数据容量信息",
      deviceQrCode: "设备二维码",
      miniProgramCode: "小程序码",
      deviceSN: "设备SN号",
      firmwareVersion: "固件版本号",
      firmwareReleaseDate: "固件发布日期",
      deviceTotalSpace: "设备总空间",
      deviceUsedSpace: "已用空间",
      deviceRemainingSpace: "剩余空间",
      registeredPersonNum: "注册人数",
      localFaceWhiteListNum: "本地人脸白名单数量",
      localPasswordWhiteListNum: "本地密码白名单数量",
      localSwipeCardWhiteListNum: "本地刷卡白名单数量",
      passLogTotalNum: "通行记录总数",
      updateDevice: "更新设备",
      currentVersion: "当前已经是最新版本，无需更新固件",
      deviceFreeSpace: "设备空闲空间",
    },
    factoryTestView: {
      title: "工厂测试",
      calibration: "摄像头标定",
    },
    localUserView: {
      title: "本地用户",
      empty: "本地尚未添加人员！",
      add: "新增人员",
      sync: "同步本地人员至小程序",
      search: "姓名或ID",
      searchBtn: "搜索",
      edit: "编辑",
      attention: "注意",
      attentionContent:
        "1、设备将同步设备本地的人员信息\n至小程序的审批列表中，执行成功\n后设备端将清除已经录入的人员信\n息。 \n2、作为管理员，您可以在小程序中\n对本地同步的人员进行审批。审批\n通过并补充完必要的字段后，组织\n内的全部设备，将拥有此次同步人\n员的通行权限。\n此操作无法撤销，请问您确定要同\n步吗？",
      tip: "提示",
      tipContent: "设备尚未连接网络，请先配置网络！",
    },
    recordQueryView: {
      title: "记录查询",
      code: "人员编号",
      time: "通行时间",
      result: "通行结果",
      stranger: "陌生人",
      face: "人脸",
      card: "刷卡",
      password: "密码",
      qrcode: "扫码",
      success: "通行成功",
      fail: "通行失败",
    },
    recordQueryDetailView: {
      title: "通行记录详情",
      id: "人员编号",
      name: "姓名",
      idCard: "身份证号",
      time: "通行时间",
      result: "通行结果",
      face: "人脸抓拍",
    },
    voiceBroadcastView: {
      title: "语音播报",
      save: "保存",
      strangerVoice: "陌生人语音",
      voiceMode: "语音模式",
      volume: "音量",
      success: "保存成功",
      fail: "保存失败",
    },
    confirm: {
      ok: "确认",
      no: "取消",
      upgrade: "设备升级",
      upgrading: "正在升级",
      upgradeSuccess: "升级成功",
      upgradeFail: "升级失败",
      cloudCertActive: "云证激活",
      cloudCertActiveSuccess: "激活成功",
      cloudCertActiveFail: "激活失败",
      restartDevice: "重启设备",
      restartDeviceDis: "配置已更新，设备即将重启",
    },
    localUserAddView: {
      title: "用户新增",
      title2: "用户编辑",
      save: "保存",
      id: "ID",
      name: "人员姓名",
      idCard: "身份证号",
      face: "人脸凭证",
      pwd: "密码凭证",
      card: "卡片凭证",
      type: "人员类型",
      input: "请输入",
      enter: "录入",
      generate: "生成",
      edit: "修改",
      reset: "重设",
      confirm: "确认",
      confirmDelete: "确认删除",
      confirmDeleteContent: "是否确认删除",
      confirmFace: "确认删除人脸凭证吗？",
      confirmPwd: "确认删除密码凭证吗？",
      confirmCard: "确认删除卡片凭证吗？",
      pwdBoxLbl: "密码生成中",
      pwdBoxSaveBtnLbl: "换一个",
      pwdBoxConfirmBtnLbl: "确定",
      cardBoxResetBtnLbl: "重置",
      cardBoxSaveBtnLbl: "保存",
      cardBoxLbl: "读取卡片中",
      cardBoxInput: "请填写用户卡号",
      delete: "删除",
      success: "成功",
      fail: "失败",
      requiredInfo: "请先填写必填信息",
      preview: "预览",
      failRepeat: "失败，用户ID重复",
      failSimilarity: "失败，人脸相似度过高",
      failCardRepeat: "失败，卡片重复",
      failPwdRepeat: "失败，密码重复",
    },
    faceEnterView: {
      title: "人脸录入",
      faceAdd: "人脸录入中，请正视摄像头",
      recogFace: "识别到人脸",
      recogSuccess: "识别成功",
      faceError: "超时未获取",
    },
    faceService: {
      contrastFailure: "对比失败",
      scalingFailure: "缩放失败",
      failedToSavePicture: "存储图片失败",
      convertToBase64Failed: "特征值转base64失败",
      base64DecodingFailed: "base64解码失败",
      similarityOverheight: "相似度过高",
      fileDoesNotExist: "文件不存在",
      theImageFormatIsNotSupported: "图片格式不支持",
      pictureReadFailure: "图片读取失败",
      thePictureSizeDoesNotMatch: "图片尺寸不符",
      imageParsingFailure: "图片解析失败",
      imageYUVProcessingFailed: "图片YUV处理失败",
      failedToConvertJpegToImage: "jpeg转image失败",
      faceInformationExtractionFailed: "人脸信息提取失败",
      theFaceIsNotUnique: "图片中人脸信息不唯一",
    }
  },
  EN: {
    mainView: {
      config: "Settings",
      pwd: "Password",
      app: "Mini Program Code",//屏蔽小程序码
      success: "Access Granted",
      fail: "Access Denied",
      passwordDisabled: "Password Access Disabled",
    },
    idleView: {
      week: {
        0: "Sun",
        1: "Mon",
        2: "Tue",
        3: "Wed",
        4: "Thu",
        5: "Fri",
        6: "Sat",
      },
    },
    appView: {
      knowed: "Got it",
      appQrcodeLbl: "Manage with Mini Program",
    },
    pwdView: {
      title: "Password Access",
      pwd: "Enter Password",
      pwdAccess: "Confirm",
      success: "Access Granted",
      fail: "Access Denied",
    },
    newPwdView: {
      title: "Set Admin Password",
      pwdAccess: "Confirm",
      pwd: "Enter Password",
      confirmPwd: "Confirm Password",
      pwdAccess: "Confirm",
      tip: "Note: Password must be at least 8 characters long. Default password will be used if skipped.",
      skip: "Skip for Now",
      success: "Password Set Successfully",
      fail: "Failed to Set Password",
      pwdNotMatch: "Passwords Don't Match",
    },
    identityVerificationView: {
      title: "Identity Verification",
      pwd: "Enter Admin Password",
      pwdAccess: "Confirm",
      success: "Face Verification Successful",
      fail: "Face Verification Failed",
      pwdLog: "Password Login",
      faceLog: "Face Login",
      pwdFail: "Wrong Password",
    },
    configView: {
      title: "Settings",
      localUser: "Local Users",
      networkSetting: "Network",
      doorControl: "Access Control",
      systemSetting: "System",
      deviceInfo: "Device Info",
      recordQuery: "Access Logs",
      voiceBroadcast: "Voice Settings",
      cloudCert: "Cloud Certificate",
      factoryTest: "Factory Test",
      help: "Help",
      confirmExit: "Exit Settings",
      confirmExitContent: "Are you sure you want to exit Settings?",
    },
    cloudCertView: {
      title: "Cloud Certificate",
      cloudCertActive: "Activate Certificate",
      inputKey: "Enter Key",
      key: "Key",
      tip: "Note: Activate using key or QR code scan. Contact support for details.",
      save: "Save",
    },
    doorControlView: {
      title: "Access Control",
      save: "Save",
      openDoorRelayDelay: "Door Release Delay",
      antiTamperAlarm: "Tamper Alarm",
      input: "Enter",
      success: "Saved",
      fail: "Save Failed",
      mqttAddr: "MQTT Server",
      mqttUser: "MQTT Username",
      mqttPwd: "MQTT Password",
      onlineChecking: "Online Verification",
      onlineCheckingTimeout: "Verification Timeout",
      ms: "ms"
    },
    helpView: {
      title: "Help",
      scanCode: "Scan for Tutorial",
    },
    networkSettingView: {
      title: "Network",
      type: "Connection Type",
      ip: "IP Address",
      dhcp: "DHCP",
      mask: "Subnet Mask",
      gateway: "Gateway",
      dns: "Primary DNS",
      dns2: "Secondary DNS",
      mac: "MAC Address",
      status: "Status",
      save: "Save",
      input: "Enter",
      ethernet: "Ethernet",
      wifi: "Wi-Fi",
      _4G: "4G",
      networkUnconnected: "Disconnected",
      networkConnected: "Connected",
      wifiName: "Network Name",
      wifiPwd: "Password",
      wifiList: "Available Networks",
      close: "Close",
      confirm: "Confirm",
      fail: "Save Failed",
      success: "Saved",
    },
    systemSettingView: {
      title: "System Settings",
      displaySetting: "Display",
      faceRecognitionSetting: "Face Recognition",
      swipeCardRecognitionSetting: "Card Access",
      passLogSetting: "Access Logs",
      passwordOpenDoorSetting: "Password Access",
      passwordManagement: "Password Management",
      timeSetting: "Date & Time",
      restartDevice: "Restart",
      restoreDefaultConfig: "Reset to Default",
      resetDevice: "Factory Reset",
      restart: "Restart",
      restoreDefault: "Reset",
      reset: "Reset",
      autoAdjustScreenBrightness: "Auto Brightness",
      screenBrightness: "Brightness",
      autoTurnOffScreen: "Auto Screen Off",
      autoTurnOffScreenTime: "Screen Off Timer",
      autoScreenSaver: "Screen Saver",
      autoScreenSaverTime: "Screen Saver Timer",
      displayIp: "Show IP Address",
      displayDeviceSn: "Show Device SN",
      language: "Language",
      displayCode: "Show Program Code",
      themeMode: "Work Theme",
      save: "Save",
      input: "Enter",
      faceSimilarityThreshold: "Face Match Threshold",
      livenessDetectionFunction: "Liveness Detection",
      livenessDetectionThreshold: "Liveness Threshold",
      infraredImageDisplay: "IR Display",
      maskRecognition: "Mask Detection",
      maskRecognitionThreshold: "Mask Detection Threshold",
      recognitionDistance: "Detection Range",
      imageSaveType: "Image Storage Type",
      saveStrangerImage: "Save Stranger Photos",
      fullView: "Full View",
      face: "Face Only",
      swipeCardRecognition: "Card Verification",
      passwordOpenDoor: "Password Access",
      inputOriginalPassword: "Enter Current Password",
      inputNewPassword: "Enter New Password",
      inputRepeatNewPassword: "Confirm New Password",
      syncMode: "Time Zone",
      ntpAddress: "NTP Server",
      timeSyncSuccess: "Time Synced Successfully",
      success: "Saved",
      fail: "Failed",
      confirmation: "Confirm",
      confirmRestart: "Confirm Restart?",
      confirmRecoveryConfiguration: "Reset to Default Settings?",
      confirmReset: "Confirm Factory Reset?",
      min: "min"
    },
    deviceInfoView: {
      title: "Device Info",
      systemInfo: "System Info",
      dataCapacityInfo: "Storage Info",
      deviceQrCode: "Device QR Code",
      miniProgramCode: "Mini Program Code",
      deviceSN: "Serial Number",
      firmwareVersion: "Firmware Version",
      firmwareReleaseDate: "Release Date",
      deviceTotalSpace: "Total Storage",
      deviceUsedSpace: "Used Storage",
      deviceRemainingSpace: "Available Storage",
      registeredPersonNum: "Registered Users",
      localFaceWhiteListNum: "Face Whitelist Count",
      localPasswordWhiteListNum: "Password Whitelist Count",
      localSwipeCardWhiteListNum: "Card Whitelist Count",
      passLogTotalNum: "Total Access Logs",
      updateDevice: "Update Device",
      currentVersion: "Device is up to date",
      deviceFreeSpace: "Free Space",
    },
    factoryTestView: {
      title: "Factory Test",
      calibration: "Camera Calibration",
      appMode: "APP Mode",
    },
    localUserView: {
      title: "Local Users",
      empty: "No Users Added",
      add: "Add User",
      sync: "Sync to Mini Program",
      search: "Search by Name or ID",
      searchBtn: "Search",
      edit: "Edit",
      attention: "Notice",
      attentionContent:
        "1. Local user data will be synced to the Mini Program approval list. After successful sync, local user data will be cleared.\n2. As an admin, you can approve synced users in the Mini Program. Once approved and required fields are completed, users will have access to all organization devices.\nThis action cannot be undone. Continue?",
      tip: "Note",
      tipContent: "Please connect to network first",
    },
    recordQueryView: {
      title: "Access Logs",
      code: "User ID",
      time: "Time",
      result: "Result",
      stranger: "Unknown",
      face: "Face",
      card: "Card",
      password: "Password",
      success: "Granted",
      fail: "Denied",
    },
    recordQueryDetailView: {
      title: "Access Log Details",
      id: "User ID",
      name: "Name",
      idCard: "ID Number",
      time: "Access Time",
      result: "Result",
      face: "Face Photo",
    },
    voiceBroadcastView: {
      title: "Voice Settings",
      save: "Save",
      strangerVoice: "Stranger Alert",
      voiceMode: "Voice Mode",
      volume: "Volume",
      success: "Saved",
      fail: "Save Failed",
    },
    confirm: {
      ok: "OK",
      no: "Cancel",
      upgrade: "Update Device",
      upgrading: "Updating...",
      upgradeSuccess: "Update Complete",
      upgradeFail: "Update Failed",
      cloudCertActive: "Activate Certificate",
      cloudCertActiveSuccess: "Activate Success",
      cloudCertActiveFail: "Activate Failed",
      restartDevice: "Restart Device",
      restartDeviceDis: "Configuration updated, device will restart",
    },
    localUserAddView: {
      title: "Add User",
      title2: "Edit User",
      save: "Save",
      id: "ID",
      name: "Name",
      idCard: "ID Number",
      face: "Face ID",
      pwd: "Password",
      card: "Access Card",
      type: "User Type",
      input: "Enter",
      enter: "Add",
      generate: "Generate",
      edit: "Edit",
      reset: "Reset",
      confirm: "Confirm",
      confirmDelete: "Confirm Delete",
      confirmDeleteContent: "Delete this item?",
      confirmFace: "Delete Face ID?",
      confirmPwd: "Delete Password?",
      confirmCard: "Delete Access Card?",
      pwdBoxLbl: "Generating...",
      pwdBoxSaveBtnLbl: "Generate New",
      pwdBoxConfirmBtnLbl: "OK",
      cardBoxResetBtnLbl: "Reset",
      cardBoxSaveBtnLbl: "Save",
      cardBoxLbl: "Reading Card...",
      cardBoxInput: "Enter Card Number",
      delete: "Delete",
      success: "Success",
      fail: "Failed",
      requiredInfo: "Required Fields Missing",
      preview: "Preview",
      failRepeat: "ID Already Exists",
      failSimilarity: "Face Too Similar",
      failCardRepeat: "Card Already Exists",
      failPwdRepeat: "Password Already Exists",
    },
    faceEnterView: {
      title: "Face Enrollment",
      faceAdd: "Look at Camera",
      recogFace: "Face Detected",
      recogSuccess: "Enrollment Complete",
      faceError: "No Face Detected",
    },
    calibrationView: {
      firstCalibration: "Initial Calibration",
      secondCalibration: "Secondary Calibration"
    },
    faceService: {
      contrastFailure: "Comparison Failed",
      scalingFailure: "Scaling Failed",
      failedToSavePicture: "Failed to Save Image",
      convertToBase64Failed: "Base64 Conversion Failed",
      base64DecodingFailed: "Base64 Decode Failed",
      similarityOverheight: "Face Too Similar",
      fileDoesNotExist: "File Not Found",
      theImageFormatIsNotSupported: "Unsupported Image Format",
      pictureReadFailure: "Failed to Read Image",
      thePictureSizeDoesNotMatch: "the picture size does not match",
      imageParsingFailure: "image parsing failure",
      imageYUVProcessingFailed: "image yuv processing failed",
      failedToConvertJpegToImage: "failed to convert jpeg to image",
      faceInformationExtractionFailed: "face information extraction failed",
      theFaceIsNotUnique: "the face is not unique",
    }
  },
};

export default messages;
